# Generated by Django 4.2 on 2023-04-25 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrangements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrangement_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby_name', models.CharField(max_length=100)),
                ('hobby_category', models.CharField(choices=[('art', 'Art'), ('spo', 'Sport'), ('act', 'Active rest'), ('cre', 'Creactivity'), ('oth', 'Others')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ARRANGEMENT.cities')),
                ('hobby', models.ManyToManyField(to='ARRANGEMENT.hobbies')),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.PositiveIntegerField()),
                ('feedback_about_user', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ARRANGEMENT.users')),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('place_address', models.CharField(max_length=100)),
                ('arrangement', models.ManyToManyField(to='ARRANGEMENT.arrangements')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ARRANGEMENT.cities')),
                ('supported_hobbies', models.ManyToManyField(to='ARRANGEMENT.hobbies')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_rating', models.PositiveIntegerField()),
                ('place_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ARRANGEMENT.places')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ARRANGEMENT.users')),
            ],
        ),
        migrations.AddField(
            model_name='arrangements',
            name='user',
            field=models.ManyToManyField(to='ARRANGEMENT.users'),
        ),
    ]
