# Generated by Django 4.2 on 2023-04-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARRANGEMENT', '0002_alter_places_arrangement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='arrangement',
            field=models.ManyToManyField(blank=True, to='ARRANGEMENT.arrangements'),
        ),
    ]
