# Generated by Django 4.2 on 2023-04-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARRANGEMENT', '0003_alter_places_arrangement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='arrangement',
        ),
        migrations.AddField(
            model_name='arrangements',
            name='place',
            field=models.ManyToManyField(blank=True, to='ARRANGEMENT.places'),
        ),
    ]
